// src/constants/slogans.js

export const SLOGAN_SETS = {

  "3PM": [
    { id: "3pm-001", groupKey: "3PM", text: "The Rangers: Because chaos keeps pirate office hours." },
    { id: "3pm-002", groupKey: "3PM", text: "We recover loudly at NARR so we don't relapse quietly at 3AM, harrr." },
    { id: "3pm-003", groupKey: "3PM", text: "The Rangers: Procrastinatin' self-destruction since today." },
    { id: "3pm-004", groupKey: "3PM", text: "If it be NARR, we're either healin' or lyin' about it." },
    { id: "3pm-005", groupKey: "3PM", text: "At NARR we don't rise and grind. We wake, panic, then recover." },
    { id: "3pm-006", groupKey: "3PM", text: "NARR: When sanity boards the ship and denial walks the plank." },
    { id: "3pm-007", groupKey: "3PM", text: "We didn't choose NARR. NARR hijacked our nervous systems." },
    { id: "3pm-008", groupKey: "3PM", text: "The Rangers: Hope, caffeine, and trauma bondin' at sea." },
    { id: "3pm-009", groupKey: "3PM", text: "NARR be where emotional damage meets pirate discipline." },
    { id: "3pm-010", groupKey: "3PM", text: "At NARR, miracles be contractually obligated to happen." },

    { id: "3pm-011", groupKey: "3PM", text: "At NARR, clean ain't our personality, but it be a decent disguise." },
    { id: "3pm-012", groupKey: "3PM", text: "Our crew has one rule: don't relapse before NARR." },
    { id: "3pm-013", groupKey: "3PM", text: "We don't hit rock bottom anymore — we penciled it in fer NARR and came here instead." },
    { id: "3pm-014", groupKey: "3PM", text: "The Rangers: We've survived worse Zoom voyages." },
    { id: "3pm-015", groupKey: "3PM", text: "NARR recovery, but make it existential, matey." },
    { id: "3pm-016", groupKey: "3PM", text: "We don't do mornings. We do NARR, harrr." },
    { id: "3pm-017", groupKey: "3PM", text: "NARR healing be cheaper than cocaine. Still costly emotionally." },
    { id: "3pm-018", groupKey: "3PM", text: "The Rangers: Turnin' emotional chaos into pirate lore." },
    { id: "3pm-019", groupKey: "3PM", text: "We don't trust mornings or feelings, but we trust NARR." },
    { id: "3pm-020", groupKey: "3PM", text: "Addiction came fer our souls. NARR negotiated visitation rights." },

    { id: "3pm-021", groupKey: "3PM", text: "The Rangers: Miracles taste like awkward honesty and stale coffee." },
    { id: "3pm-022", groupKey: "3PM", text: "At NARR we don't take ourselves seriously — just our sobriety." },
    { id: "3pm-023", groupKey: "3PM", text: "NARR: Where sarcasm meets spiritual awakenin', matey." },
    { id: "3pm-024", groupKey: "3PM", text: "NARR: The hour where shame gets thrown overboard." },
    { id: "3pm-025", groupKey: "3PM", text: "The Rangers: Not dead. Not high. Barely navigatin' — but still aboard." },
    { id: "3pm-026", groupKey: "3PM", text: "NARR: Because noon was too early fer this level o' honesty." },
    { id: "3pm-027", groupKey: "3PM", text: "The Rangers: Afternoon chaos, evenin' serenity… hopefully." },
    { id: "3pm-028", groupKey: "3PM", text: "If it's 2:59 PM, we're almost emotionally available, harrr." },
    { id: "3pm-029", groupKey: "3PM", text: "NARR: The only hour we voluntarily answer 'How be ye?'." },
    { id: "3pm-030", groupKey: "3PM", text: "The Rangers: Proof that nothing good happens after midnight, but plenty happens at NARR." },

    { id: "3pm-031", groupKey: "3PM", text: "NARR be when our feelings board the ship and our excuses abandon it." },
    { id: "3pm-032", groupKey: "3PM", text: "Some sailors take coffee breaks. We take NARR reality breaks, harrr." },
    { id: "3pm-033", groupKey: "3PM", text: "NARR: Scheduled maintenance fer spiritually glitched pirates." },
    { id: "3pm-034", groupKey: "3PM", text: "The Rangers: Turnin' 'just fer today' into 'see ye tomorrow at NARR'." },
    { id: "3pm-035", groupKey: "3PM", text: "At NARR, we ain't fine, but we be here." },
    { id: "3pm-036", groupKey: "3PM", text: "NARR: Daily reminder that we survived the dangerous waters sober." },
    { id: "3pm-037", groupKey: "3PM", text: "The Rangers: Afternoon meetin', lifetime side effects." },
    { id: "3pm-038", groupKey: "3PM", text: "NARR be the alarm bell fer our denial." },
    { id: "3pm-039", groupKey: "3PM", text: "At NARR, we stop doomscrollin' and start step-workin', matey." },
    { id: "3pm-040", groupKey: "3PM", text: "NARR: The most honest hour aboard our calendar." },
    { id: "3pm-041", groupKey: "3PM", text: "The Rangers: Because healin' before lunch feels illegal, harrr." },
    { id: "3pm-042", groupKey: "3PM", text: "NARR: Where accountability meets caffeine withdrawal at sea." },
    { id: "3pm-043", groupKey: "3PM", text: "The Rangers: Afternoons be fer honesty, not hallucinations." },
    { id: "3pm-044", groupKey: "3PM", text: "NARR: Proof the universe gives second chances after nap time, matey." },
    { id: "3pm-045", groupKey: "3PM", text: "The Rangers: Our serenity starts after noon and ends whenever the feelings mutiny." },
    { id: "3pm-046", groupKey: "3PM", text: "NARR be the only hour where confessin' insanity sounds normal." },
    { id: "3pm-047", groupKey: "3PM", text: "If it be NARR, someone be oversharin' and someone else desperately needed it." },
    { id: "3pm-048", groupKey: "3PM", text: "NARR: The hour we stop negotiatin' with addiction's HR department, harrr." },
    { id: "3pm-049", groupKey: "3PM", text: "The Rangers: Emotionally unstable, spiritually seaworthy." },
    { id: "3pm-050", groupKey: "3PM", text: "NARR: Our Higher Power knows we don't wake before noon, matey." },
    { id: "3pm-051", groupKey: "3PM", text: "At NARR we don't heal — we recalibrate the ship and hope fer calm waters." },
    { id: "3pm-052", groupKey: "3PM", text: "NARR: Sponsored by caffeine, emotional damage, and questionable pirate decisions." },
    { id: "3pm-053", groupKey: "3PM", text: "The Rangers: Yer last safe harbor before the 4PM anxiety storm." },
    { id: "3pm-054", groupKey: "3PM", text: "NARR: The hour we realize feelings ain't fatal. Just inconvenient, harrr." },
    { id: "3pm-055", groupKey: "3PM", text: "At NARR, vulnerability and sarcasm share the same cursed chair." },
    { id: "3pm-056", groupKey: "3PM", text: "NARR: Half recovery meetin', half existential pirate theatre." },
    { id: "3pm-057", groupKey: "3PM", text: "The Rangers: Where we scream internally but share externally, matey." },
    { id: "3pm-058", groupKey: "3PM", text: "NARR: The most spiritual thing we do before dinner aboard the ship." },
    { id: "3pm-059", groupKey: "3PM", text: "The Rangers: Because emotional regulation be easier after snacks." },
    { id: "3pm-060", groupKey: "3PM", text: "NARR: The hour that saved our lives more times than logic ever did, harrr." },
    { id: "3pm-061", groupKey: "3PM", text: "At NARR, we tell on our addiction before it tells on us, harrr." },
    { id: "3pm-062", groupKey: "3PM", text: "The Rangers: Our superpower be showin' up even when we'd rather abandon ship." },
    { id: "3pm-063", groupKey: "3PM", text: "NARR: If the feelings don't leave, neither do we, matey." },
    { id: "3pm-064", groupKey: "3PM", text: "NARR: Where hope clocked in even when we overslept." },
    { id: "3pm-065", groupKey: "3PM", text: "The Rangers: Every chair has trauma, and every trauma gets a chair aboard." },
    { id: "3pm-066", groupKey: "3PM", text: "NARR: If we ain't recoverin', at least we ain't usin'." },
    { id: "3pm-067", groupKey: "3PM", text: "The Rangers: Meetin' halfway between despair and dinner, harrr." },
    { id: "3pm-068", groupKey: "3PM", text: "The Rangers: Emotional support, but punctual like a proper pirate crew." },
    { id: "3pm-069", groupKey: "3PM", text: "NARR: The daily reminder that we survived the mornin' chaos sober." },
    { id: "3pm-070", groupKey: "3PM", text: "The Rangers: Because healin' at 9AM was never in the prophecy." },
    { id: "3pm-071", groupKey: "3PM", text: "NARR: Where denial steps outside fer a smoke break." },
    { id: "3pm-072", groupKey: "3PM", text: "The Rangers: We don't share trauma — we turn it into pirate lore." },
    { id: "3pm-073", groupKey: "3PM", text: "NARR: The only hour addiction can't schedule a comeback tour." },
    { id: "3pm-074", groupKey: "3PM", text: "Warnin': It be almost NARR. Feelings off the starboard side." },
    { id: "3pm-075", groupKey: "3PM", text: "NARR alert: Prepare to explain yer questionable life choices aloud." },
    { id: "3pm-076", groupKey: "3PM", text: "Reminder: At NARR, excuses expire without warning, matey." },
    { id: "3pm-077", groupKey: "3PM", text: "NARR detected. Yer denial be nearly out o' warranty." },
    { id: "3pm-078", groupKey: "3PM", text: "Incoming NARR. Silence yer ego and secure loose emotions." },
    { id: "3pm-079", groupKey: "3PM", text: "Heads up, matey: It's nearly NARR. Emotional nudity required aboard." },
    { id: "3pm-080", groupKey: "3PM", text: "Approachin' NARR. Panic responsibly, harrr." },
    { id: "3pm-081", groupKey: "3PM", text: "NARR warnin': Lies lose structural integrity in 5 minutes." },
    { id: "3pm-082", groupKey: "3PM", text: "Brace yerself. NARR be where honesty happens accidentally." },
    { id: "3pm-083", groupKey: "3PM", text: "NARR be imminent. Stretch yer coping mechanisms." },
    { id: "3pm-084", groupKey: "3PM", text: "Attention crew: NARR be not a drill. Feelings may occur." },
    { id: "3pm-085", groupKey: "3PM", text: "NARR loading… uninstall avoidance now, matey." },
    { id: "3pm-086", groupKey: "3PM", text: "Be advised: NARR punishes spiritual procrastination, harrr." },
    { id: "3pm-087", groupKey: "3PM", text: "Alert: NARR meetings may cause clarity and emotional discomfort." },
    { id: "3pm-088", groupKey: "3PM", text: "Almost NARR. Yer addiction be rehearsin' a comeback speech." },
    { id: "3pm-089", groupKey: "3PM", text: "NARR detected. Please update yer emotional software, matey." },
    { id: "3pm-090", groupKey: "3PM", text: "Warnin': At NARR ye may experience truth, humor, and suspicious amounts o' hope." },
    { id: "3pm-091", groupKey: "3PM", text: "NARR alert: The universe expects vulnerability from this crew." },
    { id: "3pm-092", groupKey: "3PM", text: "Time-sensitive notice: NARR ruins relapse plans, harrr." },
    { id: "3pm-093", groupKey: "3PM", text: "Warnin': At NARR, accountability becomes contagious aboard ship." },
    { id: "3pm-094", groupKey: "3PM", text: "NARR approaches. Bring yer humility and a beverage." },
    { id: "3pm-095", groupKey: "3PM", text: "Alert: NARR disables 'I'm fine' mode permanently." },
    { id: "3pm-096", groupKey: "3PM", text: "Warnin': At NARR yer secrets start sweatin', matey." },
    { id: "3pm-097", groupKey: "3PM", text: "Attention crew: NARR has entered the chat, harrr." },
    { id: "3pm-098", groupKey: "3PM", text: "Alert: NARR may cause unexpected self-awareness." },
    { id: "3pm-099", groupKey: "3PM", text: "NARR ahead: Prepare excuses fer immediate deletion." },
    { id: "3pm-100", groupKey: "3PM", text: "Warnin': Feelings may become sentient at NARR." },
    { id: "3pm-101", groupKey: "3PM", text: "NARR in 5 minutes. Detach from whatever lie ye be rehearsin'." },
    { id: "3pm-102", groupKey: "3PM", text: "Alert: NARR be incompatible with pretendin', matey." },
    { id: "3pm-103", groupKey: "3PM", text: "Warnin': NARR will expose at least one o' yer coping mechanisms." },
  ],

  generic: [
    { id: "gen-001", groupKey: "generic", text: "You don't have to be okay to stay clean today." },
    { id: "gen-002", groupKey: "generic", text: "Relapse lives in silence, not in honesty." },
    { id: "gen-003", groupKey: "generic", text: "Recovery is not pretty. It's consistent." },
    { id: "gen-004", groupKey: "generic", text: "You're not behind. You're just not dead yet." },
    { id: "gen-005", groupKey: "generic", text: "Your addiction hates that you're reading this instead of using." },
    { id: "gen-006", groupKey: "generic", text: "You don't have to fix your life today. Just don't burn it down." },
    { id: "gen-007", groupKey: "generic", text: "You're allowed to be a mess and still show up for your recovery." },
    { id: "gen-008", groupKey: "generic", text: "Feelings are not fatal. Ignoring them gets dangerous, though." },
    { id: "gen-009", groupKey: "generic", text: "You are not starting from zero. You're starting from experience." },
    { id: "gen-010", groupKey: "generic", text: "You didn't ruin everything. You just need a meeting and some water." },
    { id: "gen-011", groupKey: "generic", text: "Your worst day clean still beat your best day using." },
    { id: "gen-012", groupKey: "generic", text: "You don't need to deserve recovery. You just need to keep coming back." },
    { id: "gen-013", groupKey: "generic", text: "Progress in recovery is mostly: didn't use, logged in, complained honestly." },
    { id: "gen-014", groupKey: "generic", text: "You're not too broken for recovery. You're exactly built for it." },
    { id: "gen-015", groupKey: "generic", text: "You're allowed to rest. Just don't retire from recovery." },
  ],
}
