export const TOOL_PUNCHLINES = [
  "Yer addiction did not see that broadside coming, harrr.",
  "Progress feels awkward. Ye sailed through it anyway.",
  "Yer brain wanted chaos. Ye handed it pirate instructions instead.",
  "Congratulations, ye did somethin’ normal. Absolutely cursed behavior.",
  "Look at ye actin’ like a sailor with a future. Strange flex, matey.",
  "Responsibility? On this ship? Bold choice.",
  "One tiny victory. Yer nervous system be confused and alarmed.",
  "Ye chose reality over fantasy. Therapist pirate material.",
  "Look at ye, not sabotagin’ the vessel fer once. Embarrassin’.",
  "Ye didn’t implode today. The crew be disappointed.",
  "This be what recovery feels like — inconvenient, but seaworthy.",
  "Yer inner saboteur just got demoted to cabin boy.",
  "Recovery: slowly ruin’ addiction’s entire business model.",
  "Ye survived another day without dramatic self-destruction. Suspicious.",
  "Harrr, accountability strikes again.",
  "Today ye chose peace over chaos. Disgusting personal growth.",
  "Yer coping mechanisms be sweatin’ nervously.",
  "Ye patched the leak instead o’ sinkin’ the whole ship.",
  "One more day clean and yer addiction be filing complaints with management.",
  "The old ye would’ve made this worse. Character development, matey."
];